import type { DocumentType } from "./types";

/** Excel read/write use the ExcelJS library (frontend). */
export const DOCUMENT_TYPES: DocumentType[] = [
  "faktura",
  "plata",
  "smetka",
  "generic",
];

/** Options shown when user chooses document type before scanning (label + id + icon name). */
export const DOCUMENT_TYPE_CHOICES: { id: DocumentType; label: string; icon: string }[] = [
  { id: "faktura", label: "Invoices", icon: "Receipt" },
  { id: "smetka", label: "Даночен Биланс", icon: "Calculator" },
  { id: "generic", label: "ДДВ", icon: "Percent" },
  { id: "plata", label: "Плати", icon: "CreditCard" },
];

export const FIELD_KEYS = [
  "document_type",
  "invoice_number",
  "document_number",
  "date",
  "seller_name",
  "seller_address",
  "seller_tax_id",
  "seller_edb",
  "buyer_name",
  "buyer_address",
  "buyer_tax_id",
  "description",
  "net_amount",
  "tax_amount",
  "total_amount",
  "currency",
  "due_date",
  "reference",
  "payment_method",
] as const;

export type FieldKey = (typeof FIELD_KEYS)[number];

/** Required fields for profile column mapping (must be mapped to save). */
export const REQUIRED_FIELD_KEYS: FieldKey[] = [
  "invoice_number",
  "date",
  "seller_name",
  "total_amount",
];

/** Field groups for logical ordering and sections. */
export const FIELD_GROUPS = {
  document: ["document_type", "invoice_number", "document_number", "date", "reference"] as const,
  seller: ["seller_name", "seller_address", "seller_tax_id", "seller_edb"] as const,
  buyer: ["buyer_name", "buyer_address", "buyer_tax_id"] as const,
  amounts: ["description", "net_amount", "tax_amount", "total_amount", "currency"] as const,
  other: ["due_date", "payment_method"] as const,
} as const;

export const GROUP_LABELS: Record<keyof typeof FIELD_GROUPS, string> = {
  document: "Document",
  seller: "Seller",
  buyer: "Buyer",
  amounts: "Amounts",
  other: "Other",
};

export const GROUP_LABELS_MK: Record<keyof typeof FIELD_GROUPS, string> = {
  document: "Документ",
  seller: "Продавач",
  buyer: "Купувач",
  amounts: "Износи",
  other: "Друго",
};

/** Input type hint for each field (for better UX). */
export const FIELD_INPUT_TYPE: Partial<Record<FieldKey, "text" | "date" | "amount">> = {
  date: "date",
  due_date: "date",
  net_amount: "amount",
  tax_amount: "amount",
  total_amount: "amount",
};

/** Fields that use textarea (multi-line) for better content fit. */
export const FIELD_TEXTAREA: FieldKey[] = [
  "description",
  "seller_address",
  "buyer_address",
];

export const FIELD_LABELS: Record<FieldKey, string> = {
  document_type: "Document type",
  invoice_number: "Invoice number",
  document_number: "Document number (ID)",
  date: "Date",
  seller_name: "Seller name",
  seller_address: "Seller address",
  seller_tax_id: "Seller tax ID",
  seller_edb: "Seller EDB (Tax ID)",
  buyer_name: "Buyer name",
  buyer_address: "Buyer address",
  buyer_tax_id: "Buyer tax ID",
  description: "Description",
  net_amount: "Net amount",
  tax_amount: "Tax amount (VAT)",
  total_amount: "Total amount (Gross)",
  currency: "Currency",
  due_date: "Due date",
  reference: "Reference",
  payment_method: "Payment method",
};

/** Macedonian labels for fields (aligned with Excel headers). Used in Settings mapping dropdown. */
export const FIELD_LABELS_MK: Record<FieldKey, string> = {
  document_type: "Тип на документ",
  invoice_number: "Број на документ",
  document_number: "Број на фактура / ID",
  date: "Дата на документ",
  seller_name: "Продавач",
  seller_address: "Адреса на продавач",
  seller_tax_id: "Даночен број",
  seller_edb: "ЕДБ (даночен број)",
  buyer_name: "Купувач",
  buyer_address: "Адреса на купувач",
  buyer_tax_id: "Даночен број купувач",
  description: "Опис",
  net_amount: "Нето износ",
  tax_amount: "ДДВ",
  total_amount: "бруто износ",
  currency: "Валута",
  due_date: "Рок на плаќање",
  reference: "Референца",
  payment_method: "Начин на плаќање",
};

/** Keywords for OCR extraction from invoices (Macedonian-first, then English, German, etc.). */
export const KEYWORDS_MAP: Partial<Record<FieldKey, string[]>> = {
  document_type: [
    "тип на документ",
    "вид документ",
    "faktura",
    "фактура",
    "invoice",
    "rechnung",
    "document type",
    "видов документ",
  ],
  invoice_number: [
    "број на фактура",
    "број на документ",
    "broj fakture",
    "broj dokumenta",
    "invoice no",
    "invoice number",
    "rechnungsnummer",
    "rechnung nr",
    "inv no",
    "inv #",
    "doc no",
    "document no",
    "бр.",
    "br.",
    "no.",
    "#",
    "фактура бр",
    "документ бр",
    "номер фактуры",
    "invoice #",
  ],
  document_number: [
    "invoice id",
    "број на фактура",
    "број на документ",
    "document number",
    "invoice no",
    "broj fakture",
  ],
  date: [
    "датум на фактура",
    "дата на документ",
    "дата на фактура",
    "датум на издавање",
    "datum",
    "date",
    "dátum",
    "rechnungsdatum",
    "document date",
    "датум",
  ],
  seller_name: [
    "продавач",
    "испраќач",
    "издавач",
    "prodavac",
    "seller",
    "dobavljac",
    "from",
    "absender",
    "lieferant",
  ],
  seller_address: [
    "адреса на продавач",
    "адреса на испраќач",
    "seller address",
    "адреса издавач",
  ],
  seller_tax_id: [
    "едб",
    "ембс",
    "даночен број",
    "матичен број",
    "мат. број",
    "pib",
    "tax id",
    "vat id",
    "idno",
  ],
  seller_edb: [
    "едб",
    "ембс",
    "даночен број",
    "vendor tax",
    "vendor tax id",
    "pib",
    "tax id",
    "vat id",
  ],
  buyer_name: [
    "купувач",
    "примач",
    "корисник",
    "kupac",
    "buyer",
    "client",
    "to",
    "empfänger",
    "kunde",
  ],
  buyer_address: [
    "адреса на купувач",
    "адреса на примач",
    "buyer address",
    "клиент адреса",
  ],
  buyer_tax_id: [
    "даночен број купувач",
    "мат. број купувач",
    "buyer tax id",
    "куп tax",
  ],
  total_amount: [
    "бруто износ",
    "вкупно",
    "вкупно за плаќање",
    "вкупно за плаћање",
    "за наплата",
    "износ за плаќање",
    "ukupno",
    "total",
    "celkem",
    "suma",
    "bruttobetrag",
    "gesamt",
    "gross amount",
    "total amount",
    "amount due",
    "to pay",
    "za naplatu",
  ],
  net_amount: [
    "нето износ",
    "нето",
    "neto",
    "net amount",
    "nettobetrag",
    "net",
  ],
  tax_amount: [
    "ддв",
    "ддв 18%",
    "ддв 5%",
    "ддв 10%",
    "pdv",
    "vat",
    "tax",
    "mwst",
    "mwst.",
    "mehrwertsteuer",
    "данок на додадена вредност",
    "value added tax",
  ],
  currency: ["rsd", "eur", "usd", "din", "ден", "mkd", "€", "$", "валута"],
  description: [
    "опис во документ",
    "опис",
    "opis",
    "description",
    "pozicija",
    "beschreibung",
    "artikel",
    "услуги",
  ],
  due_date: [
    "рок на плаќање",
    "рок на плаћање",
    "датум на достава",
    "до датум",
    "due date",
    "fällig",
    "zahlbar",
    "payment due",
    "valuta",
    "dospelost",
  ],
  reference: [
    "договор",
    "референца",
    "referenca",
    "reference",
    "poziv na broj",
    "збор",
    "contract",
  ],
  payment_method: [
    "жиро сметка",
    "жиро",
    "bank transfer",
    "bank account",
    "transakciska",
    "gotovo",
    "начин на плаќање",
    "zahlungsart",
    "карта",
    "card",
    "уплата",
  ],
};

/** Keywords to auto-match Excel column headers (Macedonian-first; e.g. "Број на документ" → invoice_number). */
export const HEADER_KEYWORDS: Partial<Record<FieldKey, string[]>> = {
  document_type: [
    "document type",
    "тип на документ",
    "вид документ",
    "rechnung",
    "faktura",
    "invoice",
    "тип документ",
    "вид на документ",
    "даночен биланс",
    "type of document",
    "typeofdocument",
  ],
  invoice_number: [
    "invoice number",
    "invoice no",
    "invoice no.",
    "invoice #",
    "број на документ",
    "број на фактура",
    "document number",
    "broj dokument",
    "broj fakture",
    "br.",
    "no.",
    "#",
    "broj",
    "number",
    "rechnungsnummer",
    "фактура бр",
    "документ бр",
  ],
  document_number: [
    "invoice id",
    "document number",
    "број на документ",
    "број на фактура",
    "invoice no",
  ],
  date: [
    "date",
    "document date",
    "дата на документ",
    "датум на фактура",
    "datum",
    "дата",
    "датум",
    "rechnungsdatum",
    "invoice date",
    "period",
    "период",
  ],
  seller_name: [
    "seller name",
    "seller",
    "продавач",
    "prodavac",
    "dobavljac",
    "испраќач",
    "издавач",
    "supplier",
    "vendor",
  ],
  seller_address: [
    "seller address",
    "адреса продавач",
    "адреса на продавач",
    "seller addr",
    "supplier address",
  ],
  seller_tax_id: [
    "seller tax",
    "seller tax id",
    "даночен број",
    "мат. број",
    "pib",
    "vat number",
    "tax id",
    "company id",
  ],
  seller_edb: [
    "едб",
    "vendor tax id",
    "даночен број",
    "pib",
    "tax id",
    "company id",
  ],
  buyer_name: [
    "buyer name",
    "buyer",
    "купувач",
    "kupac",
    "client",
    "клиент",
    "примач",
    "customer",
  ],
  buyer_address: [
    "buyer address",
    "адреса купувач",
    "адреса на купувач",
    "buyer addr",
    "client address",
  ],
  buyer_tax_id: [
    "buyer tax",
    "buyer tax id",
    "даночен број купувач",
    "куп tax",
    "client tax",
  ],
  description: [
    "description",
    "опис",
    "опис во документ",
    "opis",
    "item",
    "items",
    "услуги",
    "services",
    "предмет",
    "subject",
  ],
  net_amount: [
    "net amount",
    "net",
    "нето износ",
    "neto",
    "nettobetrag",
    "net value",
    "subtotal",
  ],
  total_amount: [
    "total amount",
    "total",
    "gross amount",
    "бруто износ",
    "ukupno",
    "износ",
    "amount",
    "bruttobetrag",
    "sum",
    "total sum",
    "вкупно",
    "износ за плаќање",
    "јануари",
    "фебруари",
    "март",
    "април",
    "мај",
    "јуни",
    "јули",
    "август",
    "септември",
    "октомври",
    "ноември",
    "декември",
    "бруто плата",
  ],
  tax_amount: [
    "tax amount",
    "tax",
    "vat",
    "ддв",
    "ddv",
    "pdv",
    "mwst",
    "ддв 18%",
    "18%",
    "tax (vat)",
  ],
  currency: [
    "currency",
    "валута",
    "valuta",
    "curr",
  ],
  due_date: [
    "due date",
    "рок плаќање",
    "fällig",
    "payment due",
    "datum dospelosti",
  ],
  reference: [
    "reference",
    "референца",
    "збор",
    "ref",
    "poziv na broj",
  ],
  payment_method: [
    "payment method",
    "начин плаќање",
    "payment",
    "zahlungsart",
    "плаќање",
  ],
};
