import type { DocumentType } from "./types";

/** Excel read/write use the ExcelJS library (frontend). */
export const DOCUMENT_TYPES: DocumentType[] = [
  "faktura",
  "plata",
  "smetka",
  "generic",
];

/** Options shown when user chooses document type before scanning (label + id + icon name). */
export const DOCUMENT_TYPE_CHOICES: { id: DocumentType; label: string; icon: string }[] = [
  { id: "faktura", label: "Invoices", icon: "Receipt" },
  { id: "smetka", label: "Даночен Биланс", icon: "Calculator" },
  { id: "generic", label: "ДДВ", icon: "Percent" },
  { id: "plata", label: "Плати", icon: "CreditCard" },
];

export const FIELD_KEYS = [
  "document_type",
  "invoice_number",
  "document_number",
  "date",
  "seller_name",
  "seller_address",
  "seller_tax_id",
  "seller_edb",
  "buyer_name",
  "buyer_address",
  "buyer_tax_id",
  "description",
  "net_amount",
  "tax_amount",
  "total_amount",
  "currency",
  "due_date",
  "reference",
  "payment_method",
] as const;

export type FieldKey = (typeof FIELD_KEYS)[number];

/** Required fields for profile column mapping (must be mapped to save). */
export const REQUIRED_FIELD_KEYS: FieldKey[] = [
  "invoice_number",
  "date",
  "seller_name",
  "total_amount",
];

/** Field groups for logical ordering and sections. */
export const FIELD_GROUPS = {
  document: ["document_type", "invoice_number", "document_number", "date", "reference"] as const,
  seller: ["seller_name", "seller_address", "seller_tax_id", "seller_edb"] as const,
  buyer: ["buyer_name", "buyer_address", "buyer_tax_id"] as const,
  amounts: ["description", "net_amount", "tax_amount", "total_amount", "currency"] as const,
  other: ["due_date", "payment_method"] as const,
  /** Keys not in any group above (e.g. tax/smetka analyzer fields) are shown in this group. */
  extracted: [] as const,
} as const;

export const GROUP_LABELS: Record<keyof typeof FIELD_GROUPS, string> = {
  document: "Document",
  seller: "Seller",
  buyer: "Buyer",
  amounts: "Amounts",
  other: "Other",
  extracted: "Extracted",
};

export const GROUP_LABELS_MK: Record<keyof typeof FIELD_GROUPS, string> = {
  document: "Документ",
  seller: "Продавач",
  buyer: "Купувач",
  amounts: "Износи",
  other: "Друго",
  extracted: "Извлечени податоци",
};

/** Input type hint for each field (for better UX). */
export const FIELD_INPUT_TYPE: Partial<Record<FieldKey, "text" | "date" | "amount">> = {
  date: "date",
  due_date: "date",
  net_amount: "amount",
  tax_amount: "amount",
  total_amount: "amount",
};

/** Input type for analyzer/camelCase fields (Даночен биланс, ДДВ, Плати). */
export const ANALYZER_FIELD_INPUT_TYPE: Record<string, "text" | "date" | "amount"> = {
  taxYear: "text",
  year: "text",
  taxPeriod: "text",
  taxPeriodStart: "text",
  taxPeriodEnd: "text",
  // Даночен биланс (FullTaxBalanceAnalyzer) summary fields
  financialResultFromPL: "amount",
  nonRecognizedExpensesTotal: "amount",
  taxBaseBeforeReduction: "amount",
  taxBaseReductionTotal: "amount",
  taxBaseAfterReduction: "amount",
  calculatedProfitTax: "amount",
  calculatedTaxReductionTotal: "amount",
  calculatedTaxAfterReduction: "amount",
  advanceTaxPaid: "amount",
  overpaidCarriedForward: "amount",
  amountToPayOrOverpaid: "amount",
  // ДДВ (MacedonianVatReturnAnalyzer) – all numeric boxes are amounts
  totalTaxBase: "amount",
  totalOutputVat: "amount",
  totalInputVat: "amount",
  vatPayableOrRefund: "amount",
  prometOpshtaStapkaOsnova: "amount",
  prometOpshtaStapkaDDV: "amount",
  prometPovlastenaStapka10Osnova: "amount",
  prometPovlastenaStapka10DDV: "amount",
  prometPovlastenaStapka5Osnova: "amount",
  prometPovlastenaStapka5DDV: "amount",
  izvoz: "amount",
  oslobodenSOPravoNaOdbivka: "amount",
  oslobodenBezPravoNaOdbivka: "amount",
  prometNerezidentiNeOdanocliv: "amount",
  prometPrenesuvanjeDanocnaObvrska: "amount",
  primenPrometNerezidentiOpshtaOsnova: "amount",
  primenPrometNerezidentiOpshtaDDV: "amount",
  primenPrometNerezidentiPovlastenaOsnova: "amount",
  primenPrometNerezidentiPovlastenaDDV: "amount",
  primenPrometZemjaOpshtaOsnova: "amount",
  primenPrometZemjaOpshtaDDV: "amount",
  primenPrometZemjaPovlastenaOsnova: "amount",
  primenPrometZemjaPovlastenaDDV: "amount",
  vlezenPrometOsnova: "amount",
  vlezenPrometDDV: "amount",
  vlezenPrometPrijamatelStranstvoOsnova: "amount",
  vlezenPrometPrijamatelStranstvoDDV: "amount",
  vlezenPrometPrijamatelZemjaOsnova: "amount",
  vlezenPrometPrijamatelZemjaDDV: "amount",
  uvozOsnova: "amount",
  uvozDDV: "amount",
  prethodniDanociZaOdbivanje: "amount",
  ostanatiDanociIznosiZaOdbivanje: "amount",
  danochenDolgIliPobaruvanje: "amount",
  // Плати (MacedonianPayrollAnalyzer / MacedonianPayrollAnalyzer.json)
  companyName: "text",
  companyTaxId: "text",
  declarationPeriod: "text",
  brojVraboteni: "amount",
  brutoPlata: "amount",
  pridonesPIO: "amount",
  pridonesZdravstvo: "amount",
  pridonesProfesionalnoZaboluvanje: "amount",
  pridonesVrabotuvanje: "amount",
  personalenDanok: "amount",
  vkupnaNetoPlata: "amount",
  // Legacy payroll summary keys (still supported)
  totalGrossSalary: "amount",
  totalNetSalary: "amount",
  totalPayrollCost: "amount",
  ...Object.fromEntries(Array.from({ length: 59 }, (_, i) => [`aop_${i + 1}`, "amount" as const])),
};

/** All field keys that should be written as numbers in Excel (invoice + analyzer). Used for dynamic export. */
export const ALL_AMOUNT_KEYS = new Set<string>([
  "net_amount",
  "tax_amount",
  "total_amount",
  // Даночен биланс summary + AOP lines
  "financialResultFromPL",
  "nonRecognizedExpensesTotal",
  "taxBaseBeforeReduction",
  "taxBaseReductionTotal",
  "taxBaseAfterReduction",
  "calculatedProfitTax",
  "calculatedTaxReductionTotal",
  "calculatedTaxAfterReduction",
  "advanceTaxPaid",
  "overpaidCarriedForward",
  "amountToPayOrOverpaid",
  // ДДВ analyzer summary + all box amounts
  "totalTaxBase",
  "totalOutputVat",
  "totalInputVat",
  "vatPayableOrRefund",
  "prometOpshtaStapkaOsnova",
  "prometOpshtaStapkaDDV",
  "prometPovlastenaStapka10Osnova",
  "prometPovlastenaStapka10DDV",
  "prometPovlastenaStapka5Osnova",
  "prometPovlastenaStapka5DDV",
  "izvoz",
  "oslobodenSOPravoNaOdbivka",
  "oslobodenBezPravoNaOdbivka",
  "prometNerezidentiNeOdanocliv",
  "prometPrenesuvanjeDanocnaObvrska",
  "primenPrometNerezidentiOpshtaOsnova",
  "primenPrometNerezidentiOpshtaDDV",
  "primenPrometNerezidentiPovlastenaOsnova",
  "primenPrometNerezidentiPovlastenaDDV",
  "primenPrometZemjaOpshtaOsnova",
  "primenPrometZemjaOpshtaDDV",
  "primenPrometZemjaPovlastenaOsnova",
  "primenPrometZemjaPovlastenaDDV",
  "vlezenPrometOsnova",
  "vlezenPrometDDV",
  "vlezenPrometPrijamatelStranstvoOsnova",
  "vlezenPrometPrijamatelStranstvoDDV",
  "vlezenPrometPrijamatelZemjaOsnova",
  "vlezenPrometPrijamatelZemjaDDV",
  "uvozOsnova",
  "uvozDDV",
  "prethodniDanociZaOdbivanje",
  "ostanatiDanociIznosiZaOdbivanje",
  "danochenDolgIliPobaruvanje",
  // Плати analyzer (new + legacy)
  "brojVraboteni",
  "brutoPlata",
  "pridonesPIO",
  "pridonesZdravstvo",
  "pridonesProfesionalnoZaboluvanje",
  "pridonesVrabotuvanje",
  "personalenDanok",
  "totalGrossSalary",
  "totalNetSalary",
  "totalPayrollCost",
  ...Array.from({ length: 59 }, (_, i) => `aop_${i + 1}`),
]);

/** Fields that use textarea (multi-line) for better content fit. */
export const FIELD_TEXTAREA: FieldKey[] = [
  "description",
  "seller_address",
  "buyer_address",
];

export const FIELD_LABELS: Record<FieldKey, string> = {
  document_type: "Document type",
  invoice_number: "Invoice number",
  document_number: "Document number (ID)",
  date: "Date",
  seller_name: "Seller name",
  seller_address: "Seller address",
  seller_tax_id: "Seller tax ID",
  seller_edb: "Seller EDB (Tax ID)",
  buyer_name: "Buyer name",
  buyer_address: "Buyer address",
  buyer_tax_id: "Buyer tax ID",
  description: "Description",
  net_amount: "Net amount",
  tax_amount: "Tax amount (VAT)",
  total_amount: "Total amount (Gross)",
  currency: "Currency",
  due_date: "Due date",
  reference: "Reference",
  payment_method: "Payment method",
};

/** Macedonian labels for fields (aligned with Excel headers). Used in Settings mapping dropdown. */
export const FIELD_LABELS_MK: Record<FieldKey, string> = {
  document_type: "Тип на документ",
  invoice_number: "Број на документ",
  document_number: "Број на фактура / ID",
  date: "Дата на документ",
  seller_name: "Продавач",
  seller_address: "Адреса на продавач",
  seller_tax_id: "Даночен број",
  seller_edb: "ЕДБ (даночен број)",
  buyer_name: "Купувач",
  buyer_address: "Адреса на купувач",
  buyer_tax_id: "Даночен број купувач",
  description: "Опис",
  net_amount: "Нето износ",
  tax_amount: "ДДВ",
  total_amount: "бруто износ",
  currency: "Валута",
  due_date: "Рок на плаќање",
  reference: "Референца",
  payment_method: "Начин на плаќање",
};

/** AOP 1–59 labels for Даночен биланс (FullTaxBalanceAnalyzer schema). */
export const AOP_LABELS_MK: Record<string, string> = Object.fromEntries(
  Array.from({ length: 59 }, (_, i) => [`aop_${i + 1}`, `АОП ${i + 1}`])
);

/** Labels for tax/smetka (Даночен биланс) and other analyzer fields not in FIELD_KEYS. */
export const TAX_FIELD_LABELS_MK: Record<string, string> = {
  companyName: "Назив на компанија",
  companyTaxId: "ЕДБ на компанија",
  taxPeriodStart: "Даночен период од",
  taxPeriodEnd: "Даночен период до",
  ...AOP_LABELS_MK,
  // Legacy keys (kept for backward compatibility if old analyzer is used)
  taxYear: "Даночна година",
  financialResultFromPL: "Финансиски резултат (Биланс на успех)",
  nonRecognizedExpensesTotal: "Непризнаени расходи (збир)",
  taxBaseBeforeReduction: "Даночна основа (пред намалување)",
  taxBaseReductionTotal: "Намалување на даночна основа",
  taxBaseAfterReduction: "Даночна основа (по намалување)",
  calculatedProfitTax: "Пресметан данок на добивка",
  calculatedTaxReductionTotal: "Намалување на пресметан данок",
  calculatedTaxAfterReduction: "Пресметан данок (по намалување)",
  advanceTaxPaid: "Платени аконтации",
  overpaidCarriedForward: "Повеќе платен пренесен",
  amountToPayOrOverpaid: "За доплата / повеќе платено",
};

/** Labels for ДДВ (VAT return) analyzer fields. */
export const DDV_FIELD_LABELS_MK: Record<string, string> = {
  taxPeriod: "Даночен период",
  companyName: "Назив на компанија",
  companyTaxId: "ЕДБ",
  // Summary totals (bottom line of формуларот)
  totalTaxBase: "Вкупна даночна основа (01–19)",
  totalOutputVat: "Вкупен излезен ДДВ",
  totalInputVat: "Вкупен влезен ДДВ",
  vatPayableOrRefund: "ДДВ за плаќање / побарување",
  // Boxes 01–11 (acc.# 230 – излезен ДДВ)
  prometOpshtaStapkaOsnova: "01 Оданочив промет по општа стапка – основа",
  prometOpshtaStapkaDDV: "02 Оданочив промет по општа стапка – ДДВ",
  prometPovlastenaStapka10Osnova: "03 Оданочив промет по повластена стапка 10% – основа",
  prometPovlastenaStapka10DDV: "04 Оданочив промет по повластена стапка 10% – ДДВ",
  prometPovlastenaStapka5Osnova: "05 Оданочив промет по повластена стапка 5% – основа",
  prometPovlastenaStapka5DDV: "06 Оданочив промет по повластена стапка 5% – ДДВ",
  izvoz: "07 Извоз",
  oslobodenSOPravoNaOdbivka: "08 Промет ослободен со право на одбивка",
  oslobodenBezPravoNaOdbivka: "09 Промет ослободен без право на одбивка",
  prometNerezidentiNeOdanocliv: "10 Промет кон нерезиденти (неоданочлив во земјата)",
  prometPrenesuvanjeDanocnaObvrska: "11 Промет со пренесување на даночна обврска",
  primenPrometNerezidentiOpshtaOsnova: "12 Примен промет од нерезиденти по општа стапка – основа",
  primenPrometNerezidentiOpshtaDDV: "13 Примен промет од нерезиденти по општа стапка – ДДВ",
  primenPrometNerezidentiPovlastenaOsnova: "14 Примен промет од нерезиденти по повластена стапка – основа",
  primenPrometNerezidentiPovlastenaDDV: "15 Примен промет од нерезиденти по повластена стапка – ДДВ",
  primenPrometZemjaOpshtaOsnova: "16 Примен промет во земја по општа стапка – основа",
  primenPrometZemjaOpshtaDDV: "17 Примен промет во земја по општа стапка – ДДВ",
  primenPrometZemjaPovlastenaOsnova: "18 Примен промет во земја по повластена стапка – основа",
  primenPrometZemjaPovlastenaDDV: "19 Примен промет во земја по повластена стапка – ДДВ",
  // Boxes 21–31 (acc.# 130 – влезен ДДВ и даночен долг)
  vlezenPrometOsnova: "21 Влезен промет – основа",
  vlezenPrometDDV: "22 Влезен промет – ДДВ",
  vlezenPrometPrijamatelStranstvoOsnova: "23 Влезен промет за кој данокот го пресметува примателот (странство) – основа",
  vlezenPrometPrijamatelStranstvoDDV: "24 Влезен промет за кој данокот го пресметува примателот (странство) – ДДВ",
  vlezenPrometPrijamatelZemjaOsnova: "25 Влезен промет за кој данокот го пресметува примателот (земја) – основа",
  vlezenPrometPrijamatelZemjaDDV: "26 Влезен промет за кој данокот го пресметува примателот (земја) – ДДВ",
  uvozOsnova: "27 Увоз – основа",
  uvozDDV: "28 Увоз – ДДВ",
  prethodniDanociZaOdbivanje: "29 Претходни даноци за одбивање",
  ostanatiDanociIznosiZaOdbivanje: "30 Останати даноци и износи за одбивање",
  danochenDolgIliPobaruvanje: "31 Даночен долг / побарување",
  description: "Опис",
};

/** Labels for Плати (Payroll) — matches MacedonianPayrollAnalyzer.json and РД-Трошоци за вработени Excel. */
export const PAYROLL_FIELD_LABELS_MK: Record<string, string> = {
  year: "Година",
  companyName: "Име на компанија",
  companyTaxId: "Идентификационен број / ЕДБ",
  declarationPeriod: "Период за кој се поднесува (месец/година)",
  brojVraboteni: "Број на вработени за кои се пресметува плата",
  brutoPlata: "Бруто плата (Бруто 2)",
  pridonesPIO: "Придонес за ПИО",
  pridonesZdravstvo: "Придонес за здравство",
  pridonesProfesionalnoZaboluvanje: "Придонес за профес. здравствено осигурување",
  pridonesVrabotuvanje: "Придонес за вработување",
  personalenDanok: "Персонален данок",
  vkupnaNetoPlata: "Вкупно нето ефективна плата по декларација",
  totalGrossSalary: "Вкупно бруто плата",
  totalNetSalary: "Вкупно нето плата",
  totalPayrollCost: "Вкупни трошоци за вработени",
  description: "Опис",
};

/** Keywords for OCR extraction from invoices (Macedonian-first, then English, German, etc.). */
export const KEYWORDS_MAP: Partial<Record<FieldKey, string[]>> = {
  document_type: [
    "тип на документ",
    "вид документ",
    "faktura",
    "фактура",
    "invoice",
    "rechnung",
    "document type",
    "видов документ",
  ],
  invoice_number: [
    "број на фактура",
    "број на документ",
    "broj fakture",
    "broj dokumenta",
    "invoice no",
    "invoice number",
    "rechnungsnummer",
    "rechnung nr",
    "inv no",
    "inv #",
    "doc no",
    "document no",
    "бр.",
    "br.",
    "no.",
    "#",
    "фактура бр",
    "документ бр",
    "номер фактуры",
    "invoice #",
  ],
  document_number: [
    "invoice id",
    "број на фактура",
    "број на документ",
    "document number",
    "invoice no",
    "broj fakture",
  ],
  date: [
    "датум на фактура",
    "дата на документ",
    "дата на фактура",
    "датум на издавање",
    "datum",
    "date",
    "dátum",
    "rechnungsdatum",
    "document date",
    "датум",
  ],
  seller_name: [
    "продавач",
    "испраќач",
    "издавач",
    "prodavac",
    "seller",
    "dobavljac",
    "from",
    "absender",
    "lieferant",
  ],
  seller_address: [
    "адреса на продавач",
    "адреса на испраќач",
    "seller address",
    "адреса издавач",
  ],
  seller_tax_id: [
    "едб",
    "ембс",
    "даночен број",
    "матичен број",
    "мат. број",
    "pib",
    "tax id",
    "vat id",
    "idno",
  ],
  seller_edb: [
    "едб",
    "ембс",
    "даночен број",
    "vendor tax",
    "vendor tax id",
    "pib",
    "tax id",
    "vat id",
  ],
  buyer_name: [
    "купувач",
    "примач",
    "корисник",
    "kupac",
    "buyer",
    "client",
    "to",
    "empfänger",
    "kunde",
  ],
  buyer_address: [
    "адреса на купувач",
    "адреса на примач",
    "buyer address",
    "клиент адреса",
  ],
  buyer_tax_id: [
    "даночен број купувач",
    "мат. број купувач",
    "buyer tax id",
    "куп tax",
  ],
  total_amount: [
    "бруто износ",
    "вкупно",
    "вкупно за плаќање",
    "вкупно за плаћање",
    "за наплата",
    "износ за плаќање",
    "ukupno",
    "total",
    "celkem",
    "suma",
    "bruttobetrag",
    "gesamt",
    "gross amount",
    "total amount",
    "amount due",
    "to pay",
    "za naplatu",
  ],
  net_amount: [
    "нето износ",
    "нето",
    "neto",
    "net amount",
    "nettobetrag",
    "net",
  ],
  tax_amount: [
    "ддв",
    "ддв 18%",
    "ддв 5%",
    "ддв 10%",
    "pdv",
    "vat",
    "tax",
    "mwst",
    "mwst.",
    "mehrwertsteuer",
    "данок на додадена вредност",
    "value added tax",
  ],
  currency: ["rsd", "eur", "usd", "din", "ден", "mkd", "€", "$", "валута"],
  description: [
    "опис во документ",
    "опис",
    "opis",
    "description",
    "pozicija",
    "beschreibung",
    "artikel",
    "услуги",
  ],
  due_date: [
    "рок на плаќање",
    "рок на плаћање",
    "датум на достава",
    "до датум",
    "due date",
    "fällig",
    "zahlbar",
    "payment due",
    "valuta",
    "dospelost",
  ],
  reference: [
    "договор",
    "референца",
    "referenca",
    "reference",
    "poziv na broj",
    "збор",
    "contract",
  ],
  payment_method: [
    "жиро сметка",
    "жиро",
    "bank transfer",
    "bank account",
    "transakciska",
    "gotovo",
    "начин на плаќање",
    "zahlungsart",
    "карта",
    "card",
    "уплата",
  ],
};

/** Keywords to auto-match Excel column headers (Macedonian-first; e.g. "Број на документ" → invoice_number). */
export const HEADER_KEYWORDS: Partial<Record<FieldKey, string[]>> = {
  document_type: [
    "document type",
    "тип на документ",
    "вид документ",
    "rechnung",
    "faktura",
    "invoice",
    "тип документ",
    "вид на документ",
    "даночен биланс",
    "type of document",
    "typeofdocument",
  ],
  invoice_number: [
    "invoice number",
    "invoice no",
    "invoice no.",
    "invoice #",
    "број на документ",
    "број на фактура",
    "document number",
    "broj dokument",
    "broj fakture",
    "br.",
    "no.",
    "#",
    "broj",
    "number",
    "rechnungsnummer",
    "фактура бр",
    "документ бр",
  ],
  document_number: [
    "invoice id",
    "document number",
    "број на документ",
    "број на фактура",
    "invoice no",
  ],
  date: [
    "date",
    "document date",
    "дата на документ",
    "датум на фактура",
    "datum",
    "дата",
    "датум",
    "rechnungsdatum",
    "invoice date",
    "period",
    "период",
  ],
  seller_name: [
    "seller name",
    "seller",
    "продавач",
    "prodavac",
    "dobavljac",
    "испраќач",
    "издавач",
    "supplier",
    "vendor",
  ],
  seller_address: [
    "seller address",
    "адреса продавач",
    "адреса на продавач",
    "seller addr",
    "supplier address",
  ],
  seller_tax_id: [
    "seller tax",
    "seller tax id",
    "даночен број",
    "мат. број",
    "pib",
    "vat number",
    "tax id",
    "company id",
  ],
  seller_edb: [
    "едб",
    "vendor tax id",
    "даночен број",
    "pib",
    "tax id",
    "company id",
  ],
  buyer_name: [
    "buyer name",
    "buyer",
    "купувач",
    "kupac",
    "client",
    "клиент",
    "примач",
    "customer",
  ],
  buyer_address: [
    "buyer address",
    "адреса купувач",
    "адреса на купувач",
    "buyer addr",
    "client address",
  ],
  buyer_tax_id: [
    "buyer tax",
    "buyer tax id",
    "даночен број купувач",
    "куп tax",
    "client tax",
  ],
  description: [
    "description",
    "опис",
    "опис во документ",
    "opis",
    "item",
    "items",
    "услуги",
    "services",
    "предмет",
    "subject",
  ],
  net_amount: [
    "net amount",
    "net",
    "нето износ",
    "neto",
    "nettobetrag",
    "net value",
    "subtotal",
  ],
  total_amount: [
    "total amount",
    "total",
    "gross amount",
    "бруто износ",
    "ukupno",
    "износ",
    "amount",
    "bruttobetrag",
    "sum",
    "total sum",
    "вкупно",
    "износ за плаќање",
    "јануари",
    "фебруари",
    "март",
    "април",
    "мај",
    "јуни",
    "јули",
    "август",
    "септември",
    "октомври",
    "ноември",
    "декември",
    "бруто плата",
  ],
  tax_amount: [
    "tax amount",
    "tax",
    "vat",
    "ддв",
    "ddv",
    "pdv",
    "mwst",
    "ддв 18%",
    "18%",
    "tax (vat)",
  ],
  currency: [
    "currency",
    "валута",
    "valuta",
    "curr",
  ],
  due_date: [
    "due date",
    "рок плаќање",
    "fällig",
    "payment due",
    "datum dospelosti",
  ],
  reference: [
    "reference",
    "референца",
    "збор",
    "ref",
    "poziv na broj",
  ],
  payment_method: [
    "payment method",
    "начин плаќање",
    "payment",
    "zahlungsart",
    "плаќање",
  ],
};
